name: Test

on: 
 pull_request:
  types: [labeled,synchronize,unlabeled,edited]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: powers2537/bump-package-version-sample@main
        with:
          path: 'right_here'
